spring:
  application:
    name: mall-admin
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      #redis
  redis:
    host: 127.0.0.1
    port: 6379
    #datasource
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#      扫描Mappeer接口对应xml文件

#配置redis
#redis:
#  database:mall
#  key:
#    admin: 'ums:admin'
#    resourceList: 'ums:resourceList'
#  expire:
#    common:86400

#springSecurity拦截白名单
secure:
  ignored:
    urls:
      - /swagger-ui.html
        - /swagger-resources/**
        - /swagger/**
        - /**/v2/api-docs
        - /**/*.js
        - /**/*.css
        - /**/*.png
        - /**/*.ico
        - /webjars/springfox-swagger-ui/**
        - /actuator/**
        - /druid/**
        - /admin/login
        - /admin/register
        - /admin/info
        - /admin/logout
        - /minio/upload